# Generated by Django 3.1.7 on 2021-03-30 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_update',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 3, 30, 12, 21, 8, 458443, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 3, 30, 12, 21, 23, 941287, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
