# Generated by Django 3.1.7 on 2021-03-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210330_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
