# Generated by Django 3.1.7 on 2021-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210330_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
